<div class="content" style="">
                <iframe frameborder="0" marginwidth="0" marginheight="0" src="http://thienduongweb.com/tool/weather/?r=1&w=1&g=1&d=0" width="100%" height="370" scrolling="yes"></iframe>
        </div>
        <div class="space" style="background-color: white;
                                height: 400px;
                                width: 500px;
                                position: absolute;
                                top: 18%;
                                left: 5%"></div>